INSERT INTO ROLE (CODE) VALUES ('ADMIN');
INSERT INTO ROLE (CODE) VALUES ('USER');

INSERT INTO USER (CREATION_DATE, LAST_MODIFIED_DATE, EMAIL, PASSWORD, ROLE_ID, USERNAME)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'admin@blog.com', 'admin', 1, 'admin');