INSERT INTO ROLE (CODE) VALUES ('ADMIN');
INSERT INTO ROLE (CODE) VALUES ('USER');

INSERT INTO USER (CREATION_DATE, LAST_MODIFIED_DATE, EMAIL, PASSWORD, ROLE_ID, USERNAME) VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'admin@blog.com', '$2a$10$IvmvTi.XM3KX26C10mXxVueaVhIbveSNowG4d2mzUvfbMF3Op2bVe', 1, 'admin');